import coverBook from '../assets/cover-book.png';

export const mockedBooks = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    cover: coverBook,
    price: 10,
    description: 'A powerful story of racial injustice and childhood innocence in the American South.',
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    cover: coverBook,
    price: 15,
    description: 'A dystopian novel about totalitarianism, surveillance, and control.',
  },
  {
    id: 3,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    cover: coverBook,
    price: 12,
    description: 'A classic romance novel exploring love, class, and societal expectations.',
  },
  {
    id: 4,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    cover: coverBook,
    price: 14,
    description: 'A story of ambition, wealth, and the American Dream set in the Jazz Age.',
  },
  {
    id: 5,
    title: 'Moby Dick',
    author: 'Herman Melville',
    cover: coverBook,
    price: 18,
    description: 'An epic tale of obsession and revenge on the high seas.',
  },
  {
    id: 6,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    cover: coverBook,
    price: 20,
    description: 'A sweeping novel of Russian society during the Napoleonic era.',
  },
  {
    id: 7,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    cover: coverBook,
    price: 10,
    description: 'A story of teenage angst and alienation, narrated by Holden Caulfield.',
  },
  {
    id: 8,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    cover: coverBook,
    price: 13,
    description: 'A fantasy adventure following Bilbo Baggins on a quest through Middle-earth.',
  },
  {
    id: 9,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    cover: coverBook,
    price: 11,
    description: 'A dystopian novel that explores a society driven by pleasure and control.',
  },
  {
    id: 10,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    cover: coverBook,
    price: 16,
    description: 'An exploration of morality, guilt, and redemption in 19th-century Russia.',
  },
  {
    id: 11,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    cover: coverBook,
    price: 25,
    description: 'An epic fantasy trilogy about the quest to destroy the One Ring.',
  },
  {
    id: 12,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    cover: coverBook,
    price: 12,
    description: 'A classic novel about love, independence, and resilience.',
  },
  {
    id: 13,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    cover: coverBook,
    price: 20,
    description: 'A journey through Hell, Purgatory, and Paradise, exploring human virtue and vice.',
  },
  {
    id: 14,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    cover: coverBook,
    price: 19,
    description: 'A philosophical novel on faith, family, and the nature of good and evil.',
  },
  {
    id: 15,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    cover: coverBook,
    price: 17,
    description: 'A magical realist saga of the Buendía family in the town of Macondo.',
  },
  {
    id: 16,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    cover: coverBook,
    price: 10,
    description: 'A groundbreaking novel about science, creation, and the consequences of ambition.',
  },
  {
    id: 17,
    title: 'Ulysses',
    author: 'James Joyce',
    cover: coverBook,
    price: 22,
    description: 'A modernist novel following Leopold Bloom’s journey through Dublin in a single day.',
  },
  {
    id: 18,
    title: 'The Odyssey',
    author: 'Homer',
    cover: coverBook,
    price: 15,
    description: 'The epic tale of Odysseus’s ten-year journey home after the Trojan War.',
  },
  {
    id: 19,
    title: 'Meditations',
    author: 'Marcus Aurelius',
    cover: coverBook,
    price: 12,
    description: 'A series of personal reflections on philosophy, virtue, and the Stoic way of life.',
  },
  {
    id: 20,
    title: 'The Iliad',
    author: 'Homer',
    cover: coverBook,
    price: 14,
    description: 'An epic poem about the Trojan War and the heroic deeds of Achilles.',
  },
  {
    id: 21,
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    cover: coverBook,
    price: 18,
    description: 'A tragic love story that critiques Russian society and its values.',
  },
  {
    id: 22,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    cover: coverBook,
    price: 17,
    description: 'A thrilling tale of betrayal, revenge, and redemption.',
  },
  {
    id: 23,
    title: 'Les Misérables',
    author: 'Victor Hugo',
    cover: coverBook,
    price: 20,
    description: 'A sweeping novel about justice, mercy, and redemption in 19th-century France.',
  },
  {
    id: 24,
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    cover: coverBook,
    price: 15,
    description: 'A story of hardship, hope, and resilience during the Great Depression.',
  },
  {
    id: 25,
    title: 'Dracula',
    author: 'Bram Stoker',
    cover: coverBook,
    price: 10,
    description: 'A classic horror novel about the infamous vampire Count Dracula.',
  },
  {
    id: 26,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    cover: coverBook,
    price: 11,
    description: 'A dark tale of love, revenge, and madness on the Yorkshire moors.',
  },
  {
    id: 27,
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    cover: coverBook,
    price: 13,
    description: 'A historical novel set during the turbulent years of the French Revolution.',
  },
  {
    id: 28,
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    cover: coverBook,
    price: 18,
    description: 'A humorous and philosophical novel about a man who imagines himself a knight.',
  },
  {
    id: 29,
    title: 'Catch-22',
    author: 'Joseph Heller',
    cover: coverBook,
    price: 12,
    description: 'A satirical novel about the absurdity of war and military bureaucracy.',
  },
  {
    id: 30,
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    cover: coverBook,
    price: 10,
    description: 'A dystopian novel about censorship and the burning of books.',
  },
];
